### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by wenzhixin** [guohuadeng/magento-app-v2#2]
- [x] use angular ajax instead of jquery ajax.
- [x] deploy apk build server.
- [x] update ionic and angular to the latest version.
- [x] build iOS package (ipa).
