### ISSUE TITLE
Todo list add

### ISSUE THREAD

**Issue by guohuadeng** [guohuadeng/magento-app-v2#3]
- [x] remove angular-material, use normal footer tab.
- [x] multi-language version, chinese first.
- [x] support auto price calculate with different option.

**Comment by wenzhixin** [comment]
自动计算的话，那些颜色大小的如何算？公式？
